version: '3.8'

services:
  frontend:
    build:
      context: ./webnovel-manager
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://192.168.1.87:8001
    ports:
      - "8080:8080"
    environment:
      - NEXT_PUBLIC_API_URL=http://192.168.1.87:8001
    depends_on:
      - backend
    networks:
      - default

  backend:
    build:
      context: ./webnovel-manager-api
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - DEBUG=1  # 1 para usar Google Translate, 0 para DeepL
      - DEEPL_API_KEY=tu_api_key_aqui
      - TARGET_LANGUAGE=ES
    networks:
      - default
      - mongodb_default

networks:
  default:
    name: webnovel-manager_default
  mongodb_default:
    external: true 